Magni/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, register_converter

import apps.base.views


class IdUrlConverter:
    regex = "[0-9]{6}"

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return "%06d" % value


register_converter(IdUrlConverter, "id")


urlpatterns = [
    path("", apps.base.views.view_index, name="home"),
    path("privacy", apps.base.views.view_privacy, name="privacy"),

    path("activities/", include("apps.activities.urls")),
    path("user/", include("apps.user.urls")),
    path("equipments/", include("apps.equipments.urls")),
    path("weight/", include("apps.weight.urls")),
    path("competitions/", include("apps.competitions.urls")),
    path("goals/", include("apps.goals.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

apps/goals/urls.py
from django.urls import path

from apps.goals import views


urlpatterns = [
    path("", views.view_goals, name="goals"),
    path("add", views.view_goal_create, name="add_goal"),
    path("<id:gid>/edit", views.view_goal_edit, name="edit_goal"),
    #path("<int:gid>/edit", views.view_goal_edit_redirect),
    path("<id:gid>/remove", views.view_goal_remove, name="remove_goal"),
    #path("<int:gid>/remove", views.view_goal_remove_redirect),
    path("<id:gid>/validate", views.view_goal_validate, name="validate_goal"),
]

apps/activities/models.py
import datetime
import json
import os

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.timezone import make_naive
from django.utils.translation import gettext as _

from Magni.settings import BASE_DIR
from apps.base.globals import sports
from apps.activities.trackfile import TrackFile
from apps.competitions.models import Competition
from apps.equipments.models import Equipment
from apps.user.models import User


class Activity(models.Model):
    date = models.DateTimeField(_("date"))
    name = models.CharField(_("name"), max_length=100, blank=True, null=True)
    time_shift = models.SmallIntegerField(_("time shift"), validators=[MinValueValidator(-12*60), MaxValueValidator(12*60)], default=0)
    type = models.CharField(_("activity type"), max_length=16, choices=[(a, b["name"]) for a, b in sports.items()], default="Other")
    planned = models.BooleanField(_("planned activity"), default=False)
    duration = models.PositiveIntegerField(_("duration"), blank=True, null=True)
    duration_total = models.PositiveIntegerField(_("total duration"), blank=True, null=True)
    distance = models.PositiveIntegerField(_("distance"), blank=True, null=True)
    notes = models.TextField(_("notes"), max_length=1000, blank=True)
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="activities", on_delete=models.CASCADE)
    device = models.CharField(_("device"), max_length=50, blank=True)
    heart_rate_avg = models.PositiveSmallIntegerField(_("average heart rate"), validators=[MaxValueValidator(220)], blank=True, null=True)
    heart_rate_max = models.PositiveSmallIntegerField(_("maximum heart rate"), validators=[MaxValueValidator(220)], blank=True, null=True)
    cadence_avg = models.PositiveSmallIntegerField(_("average cadence"), blank=True, null=True)
    cadence_max = models.PositiveSmallIntegerField(_("maximum cadence"), blank=True, null=True)
    power_avg = models.PositiveSmallIntegerField(_("average power"), blank=True, null=True)
    power_max = models.PositiveSmallIntegerField(_("maximum power"), blank=True, null=True)
    speed_avg = models.FloatField(_("average speed"), blank=True, null=True)
    speed_max = models.FloatField(_("maximum speed"), blank=True, null=True)
    calories = models.PositiveSmallIntegerField(_("calories"), blank=True, null=True)
    elevation_gain = models.PositiveIntegerField(_("elevation gain"), blank=True, null=True)
    elevation_loss = models.PositiveIntegerField(_("elevation loss"), blank=True, null=True)
    trimp = models.PositiveSmallIntegerField(_("TRIMP"), blank=True, null=True)
    level = models.PositiveSmallIntegerField(_("level"), blank=True, null=True)
    tss = models.PositiveSmallIntegerField(_("TSS"), blank=True, null=True)
    ngp = models.FloatField(_("NGP"), blank=True, null=True)
    feeling = models.PositiveSmallIntegerField(_("feeling"), default=0, validators=[MaxValueValidator(5)])
    exertion = models.PositiveSmallIntegerField(_("exertion"), default=0, validators=[MaxValueValidator(10)])
    equipments = models.ManyToManyField(Equipment, verbose_name=_("equipments"), related_name="activities", blank=True)
    competition = models.ForeignKey(Competition, verbose_name=_("competition"), related_name="activities", blank=True, null=True, on_delete=models.SET_NULL)
    data = models.TextField(_("data"), blank=True, null=True)  # format JSON

    # TODO: links

    def __init__(self, *args, **kwargs):
        self.trackfile = TrackFile()
        super(Activity, self).__init__(*args, **kwargs)

    def __str__(self):
        return "%s (%s) by %s" % (str(self.date), self.type, self.user)

    @property
    def date_local(self):
        return self.date.replace(tzinfo=None) + datetime.timedelta(seconds=self.time_shift * 60)

    @property
    def date_user(self):
        return make_naive(self.date)

    class Meta:
        verbose_name = _("Activity")
        verbose_name_plural = _("Activities")
        ordering = ["-date"]


def export_activity_json(activity):
    response = {
        "date": activity.date,
        "type": activity.type,
        "files": [],
    }

    if activity.duration is not None:
        response["duration"] = activity.duration
    if activity.duration_total is not None:
        response["duration_total"] = activity.duration_total
    if activity.distance is not None:
        response["distance"] = activity.distance
    if activity.notes:
        response["notes"] = activity.notes
    if activity.device is not None:
        response["device"] = activity.device
    if activity.trimp is not None:
        response["trimp"] = activity.trimp
    if activity.ngp is not None:
        response["ngp"] = activity.ngp
    if activity.speed_avg is not None:
        response["speed_avg"] = activity.speed_avg
    if activity.speed_max is not None:
        response["speed_max"] = activity.speed_max
    if activity.cadence_avg is not None:
        response["cadence_avg"] = activity.cadence_avg
    if activity.cadence_max is not None:
        response["cadence_max"] = activity.cadence_max
    if activity.power_avg is not None:
        response["power_avg"] = activity.power_avg
    if activity.power_max is not None:
        response["power_max"] = activity.power_max
    if activity.elevation_gain is not None:
        response["elevation_gain"] = activity.elevation_gain
    if activity.elevation_loss is not None:
        response["elevation_loss"] = activity.elevation_loss
    if activity.heart_rate_avg is not None:
        response["heart_rate_avg"] = activity.heart_rate_avg
    if activity.heart_rate_max is not None:
        response["heart_rate_max"] = activity.heart_rate_max
    if activity.calories is not None:
        response["calories"] = activity.calories
    if activity.feeling:
        response["feeling"] = activity.feeling
    if activity.exertion:
        response["exertion"] = activity.exertion

    if activity.data:
        try:
            data = json.loads(activity.data)
        except:
            data = {}

        if "records" in data and data["records"]:
            response["records"] = data["records"]
        if "pauses" in data and data["pauses"]:
            response["pauses"] = data["pauses"]
        if "heartrate_stats" in data and data["heartrate_stats"]:
            response["heartrate_stats"] = data["heartrate_stats"]
        if "power_stats" in data and data["power_stats"]:
            response["power_stats"] = data["power_stats"]
        if "segments" in data and data["segments"]:
            response["segments"] = data["segments"]

    response["equipments"] = []
    for equipment in activity.equipments.all():
        response["equipments"].append(str(equipment))

    if activity.competition:
        response["competition"] = activity.competition.name

    # Files
    for file in activity.files.all():
        response["files"].append({
            "name": file.filename,
            "sha1": file.filehash,
            "size": file.filesize,
            "compressed_size": file.compressed_size,
        })

    return response


class ActivityFile(models.Model):
    activity = models.ForeignKey(Activity, verbose_name=_("activity"), related_name="files", on_delete=models.CASCADE)
    filename = models.CharField(_("file name"), max_length=100)
    filehash = models.CharField(_("file hash"), max_length=40)
    filesize = models.PositiveIntegerField(_("file size"), default=0)
    compressed_size = models.PositiveIntegerField(_("compressed size"), default=0)
    # TODO: ajouter le format du fichier (TCX, FIT, etc.)
    # TODO: ajouter les types de données contenus dans le fichier (fréquence cardiaque, puissance, etc.)

    def __str__(self):
        return "%s \"%s\" (activity %s)" % (self.filehash, self.filename, self.activity)

    @property
    def downloadable(self):
        # Check if file is available in storage
        return os.path.isfile(self.get_path)

    @property
    def get_path(self):
        return os.path.join(BASE_DIR, "data", "files", str(self.filehash) + ".gz")

    class Meta:
        verbose_name = _("Activity file")
        verbose_name_plural = _("Activity files")
        unique_together = ("activity", "filehash")
        ordering = ["filename"]


class Note(models.Model):
    date_start = models.DateTimeField(_("start date"))
    date_end = models.DateTimeField(_("end date"), blank=True, null=True)
    title = models.CharField(_("title"), max_length=100)
    content = models.TextField(_("content"), max_length=1000, blank=True)
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="notes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Note")
        verbose_name_plural = _("Notes")
        ordering = ["date_start", "date_end"]

apps/goals/forms.py
import re

from django.forms import Form
from django.forms import IntegerField, TextInput, BooleanField, CharField, ChoiceField, DateField, TimeField
from django.utils.translation import gettext as _, pgettext

from apps.base.globals import sports
from apps.base.forms import convert_duration_string
from apps.base.forms import HTML5DateInput


class GoalForm(Form):
    type = ChoiceField(label=_("Goal type"), choices=[("activity", _("Per activity")), ("week", _("Per week")), ("month", _("Per month")), ("year", _("Per year")), ("other", pgettext("goal", "Other")),])
    sport = ChoiceField(label=_("Activity type"), choices=[("All", _("All"))] + [(a, b["name"]) for a, b in sports.items()], required=False)
    criteria = ChoiceField(label=_("Criteria"), choices=[("distance", _("Distance")), ("duration", _("Duration")), ("trimp", _("TRIMP")), ("count", _("Activity count")), ("record-distance", _("Distance record")), ("record-duration", _("Duration record")),], required=False)
    distance = IntegerField(label=_("Distance"), min_value=0, required=False, initial=1000)
    duration = CharField(label=_("Duration"), max_length=20, required=False, widget=TextInput(attrs={"placeholder": "HH:MM:SS"}))
    count = IntegerField(label=_("Activity count"), min_value=1, required=False, initial=1)
    trimp = IntegerField(label=_("TRIMP"), min_value=0, required=False, initial=100)
    repetition = BooleanField(label=_("Repetition"), required=False)
    description = CharField(label=_("Description"), max_length=80, required=False, help_text=_("You can override the description generated by the application."))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        try:
            s, ms = divmod(self.initial["duration"], 1000)
            value_h = s // 3600
            value_m = (s % 3600) // 60
            value_s = (s % 60)
            self.initial["duration"] = _("%(hours)02d:%(minutes)02d:%(seconds)02d") % {"hours": value_h, "minutes": value_m, "seconds": value_s}
        except:
            pass

    def clean_duration(self):
        duration = convert_duration_string(self.cleaned_data["duration"])
        if duration is None:
            return 0
        else:
            return duration

    def clean(self):
        cleaned_data = super().clean()
        value_type = cleaned_data.get("type")
        value_criteria = cleaned_data.get("criteria")

        if value_type == "activity":
            if value_criteria == "count":
                self.add_error("criteria", _("Invalid criteria."))
        elif value_type == "other":
            if cleaned_data.get("description").strip() == "":
                self.add_error("description", _("Invalid description."))
        else:
            if value_criteria in ["record-duration", "record-distance"]:
                self.add_error("criteria", _("Invalid criteria."))

        if value_type != "other":
            if value_criteria in ["duration", "record-duration", "record-distance"]:
                value_duration = cleaned_data.get("duration")
                if value_duration is None or value_duration <= 0:
                    self.add_error("duration", _("Invalid duration."))

            if value_criteria in ["distance", "record-duration", "record-distance"]:
                value_distance = cleaned_data.get("distance")
                if value_distance is None or value_distance <= 0:
                    self.add_error("distance", _("Invalid distance."))

            if value_criteria == "count":
                value_count = cleaned_data.get("count")
                if value_count is None or value_count <= 0:
                    self.add_error("count", _("Invalid activity count."))
            elif value_criteria == "trimp":
                value_trimp = cleaned_data.get("trimp")
                if value_trimp is None or value_trimp <= 0:
                    self.add_error("trimp", _("Invalid TRIMP."))


class GoalValidateForm(Form):
    date = DateField(label=_("Date"), required=True, widget=HTML5DateInput(format="%Y-%m-%d"))
    time = TimeField(label=pgettext("datetime", "Time"), required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.initial["date"] = ""  # TODO
        self.initial["time"] = ""  # TODO

apps/goals/templates/goals/goal_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load utils %}

{% block title %}{% translate 'Goals' %} | {% endblock %}
{% block page_title %}{% translate 'Create goal' %}{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post">
    {% csrf_token %}

    <div class="card-body">
      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
          <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% block button_text %}{% translate 'Create' %}{% endblock %}" />
      <a href="{% url 'goals' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(function() {
  var type = null;
  var criteria = null;

  function updateType() {
    type = $('#id_type').val();

    if (type == 'other') {
      $('#id_sport').prop('disabled', true).parent().parent().hide();
      $('#id_criteria').prop('disabled', true).parent().parent().hide();
      $('#id_distance').prop('disabled', true).parent().parent().hide();
      $('#id_duration').prop('disabled', true).parent().parent().hide();
      $('#id_count').prop('disabled', false).parent().parent().hide();
      $('#id_trimp').prop('disabled', true).parent().parent().hide();
      $('#id_repetition').prop('disabled', true).parent().parent().hide();

      $('#id_description').parent().children('.form-text').hide();
    } else {
      $('#id_sport').prop('disabled', false).parent().parent().show();
      $('#id_criteria').prop('disabled', false).parent().parent().show();

      $('#id_description').parent().children('.form-text').show();

      if (type == 'activity') {
        $('#id_criteria').children('option[value="count"]').remove();

        if ($('#id_criteria').children('option[value="record-duration"]').length == 0)
          $('#id_criteria').append('<option value="record-duration">{% translate 'Duration record'|escapejs %}</option>');
        if ($('#id_criteria').children('option[value="record-distance"]').length == 0)
          $('#id_criteria').append('<option value="record-distance">{% translate 'Distance record'|escapejs %}</option>');

        $('#id_repetition').prop('disabled', true).parent().parent().hide();
      } else {
        $('#id_criteria').children('option[value="record-duration"]').remove();
        $('#id_criteria').children('option[value="record-distance"]').remove();

        if ($('#id_criteria').children('option[value="count"]').length == 0)
          $('#id_criteria').append('<option value="count">{% translate 'Activity count'|escapejs %}</option>');

        $('#id_repetition').prop('disabled', false).parent().parent().show();
      }

      updateCriteria();
    }
  }

  function updateCriteria() {
    criteria = $('#id_criteria').val();

    if (type == 'other') {
      return;
    }

    if (criteria == 'distance') {
      $('#id_distance').prop('disabled', false).parent().parent().show();
      $('#id_duration').prop('disabled', true).parent().parent().hide();
      $('#id_count').prop('disabled', true).parent().parent().hide();
      $('#id_trimp').prop('disabled', true).parent().parent().hide();
    } else if (criteria == 'duration') {
      $('#id_distance').prop('disabled', true).parent().parent().hide();
      $('#id_duration').prop('disabled', false).parent().parent().show();
      $('#id_count').prop('disabled', true).parent().parent().hide();
      $('#id_trimp').prop('disabled', true).parent().parent().hide();
    } else if (criteria == 'count') {
      $('#id_distance').prop('disabled', true).parent().parent().hide();
      $('#id_duration').prop('disabled', true).parent().parent().hide();
      $('#id_count').prop('disabled', false).parent().parent().show();
      $('#id_trimp').prop('disabled', true).parent().parent().hide();
    } else if (criteria == 'trimp') {
      $('#id_distance').prop('disabled', true).parent().parent().hide();
      $('#id_duration').prop('disabled', true).parent().parent().hide();
      $('#id_count').prop('disabled', true).parent().parent().hide();
      $('#id_trimp').prop('disabled', false).parent().parent().show();
    } else if (criteria == 'record-duration' || criteria == 'record-distance') {
      $('#id_distance').prop('disabled', false).parent().parent().show();
      $('#id_duration').prop('disabled', false).parent().parent().show();
      $('#id_count').prop('disabled', true).parent().parent().hide();
      $('#id_trimp').prop('disabled', true).parent().parent().hide();
    } else {
      $('#id_distance').prop('disabled', true).parent().parent().hide();
      $('#id_duration').prop('disabled', true).parent().parent().hide();
      $('#id_count').prop('disabled', true).parent().parent().hide();
      $('#id_trimp').prop('disabled', true).parent().parent().hide();
    }
  }

  $('#id_type').change(function() {
    updateType();
  });

  $('#id_criteria').change(function() {
    updateCriteria();
  });

  updateType();
});
</script>
{% endblock %}

apps/goals/templates/goals/goal_edit.html
{% extends 'goals/goal_create.html' %}
{% load i18n %}

{% block page_title %}{% translate 'Edit goal' %}{% endblock %}
{% block button_text %}{% translate 'Edit' %}{% endblock %}

apps/goals/templates/goals/goal_remove.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate 'Goals' %} | {% endblock %}
{% block page_title %}{% translate 'Remove goal' %}{% endblock %}

{% block content %}

<div class="card card-primary">
  <form action="" method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="delete" value="1" />

    <div class="card-body">
      <p>{% translate 'Goal' %}{% translate ':' %} <q>{{ goal.description|safe }}</q></p>

      <div class="alert alert-warning">
        <p>{% translate 'Are you sure you want to remove this goal?' %}</p>
        <p><i class="icon fas fa-exclamation-triangle"></i>{% translate 'This action is irreversible.' %}</p>
      </div>
    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-danger" value="{% translate 'Remove' %}" />
      <a href="{% url 'goals' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

apps/goals/templates/goals/goal_validate.html
{% extends 'base.html' %}
{% load i18n %}
{% load utils %}
{% load static %}

{% block title %}{% translate 'Goals' %} | {% endblock %}
{% block page_title %}{% translate 'Validate goal' %}{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/jquery.timepicker/jquery.timepicker.css' %}" />
{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post">
    {% csrf_token %}

    <div class="card-body">
      <p>{% translate 'Goal' %}{% translate ':' %} <q>{{ goal.description|safe }}</q></p>

      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
          <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Validate' %}" />
      <a href="{% url 'goals' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.timepicker/jquery.timepicker.js' %}"></script>
<script type="text/javascript">
$(function() {
  $('#id_time').timepicker({'timeFormat': 'H:i:s'});
});
</script>
{% endblock %}

apps/goals/templates/goals/goals.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% translate 'Goals' %} | {% endblock %}
{% block page_title %}{% translate 'Goals' %}{% endblock %}

{% block page_title_buttons %}
<div>
  <a href="{% url 'add_goal' %}" class="btn btn-primary btn-sm">{% translate 'Create goal' %}</a>
</div>
{% endblock %}

{% block content %}

<div class="card">
  {% if goals %}
  <div class="card-body p-0">
    <table class="table table-bordered table-striped table-sm">
      <thead>
        <tr>
          <th>{% translate 'Goal' %}</th>
          <th colspan="2">{% translate 'Progression' %}</th>
          <th>{% translate 'Date' %}</th>
          <th>{% translate 'Actions' %}</th>
        </tr>
      </thead>
      <tbody>
      {% for goal in goals %}
        <tr>
          <td>{{ goal.description|safe }}</td>
          <td style="width: 200px;">
            {% if goal.type == 'other' %}
              {% if not goal.accomplished %}
              <a href="{% url 'validate_goal' forloop.counter0 %}" class="btn btn-xs btn-primary">{% translate 'Validate' %}</a>
              {% endif %}
            {% else %}
            <div class="progress progress-xs progress-striped active">
              <div class="progress-bar {% if goal.progression.percentage >= 100 %}bg-success{% elif goal.progression.percentage > 50 %}bg-warning{% else %}bg-danger{% endif %}" style="width: {{ goal.progression.percentage|stringformat:'f' }}%"></div>
            </div>
            {% endif %}
          </td>
          <td style="width: 36px;">
            {% if goal.type == 'other' %}
              {% if goal.accomplished %}
              <span class="badge bg-success">{% translate 'OK' %}</span>
              {% endif %}
            {% else %}
            <span class="badge {% if goal.progression.percentage >= 100 %}bg-success{% elif goal.progression.percentage > 50 %}bg-warning{% else %}bg-danger{% endif %}">{{ goal.progression.percentage|stringformat:'d' }}%</span>
            {% endif %}
          </td>
          <td>{% if goal.accomplished and goal.progression.date %}{{ goal.progression.date }}{% endif %}</td>
          <td><a href="{% url 'edit_goal' forloop.counter0 %}" class="btn btn-xs btn-warning">{% translate 'Edit' %}</a> <a href="{% url 'remove_goal' forloop.counter0 %}" class="btn btn-xs btn-danger">{% translate 'Remove' %}</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
  <div class="card-body">
    <p>{% translate 'No goals.' %}</p>
  {% endif %}
  </div>
</div>

{% endblock %}