Magni/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, register_converter

import apps.base.views


class IdUrlConverter:
    regex = "[0-9]{6}"

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return "%06d" % value


register_converter(IdUrlConverter, "id")


urlpatterns = [
    path("", apps.base.views.view_index, name="home"),
    path("privacy", apps.base.views.view_privacy, name="privacy"),

    path("activities/", include("apps.activities.urls")),
    path("user/", include("apps.user.urls")),
    path("equipments/", include("apps.equipments.urls")),
    path("weight/", include("apps.weight.urls")),
    path("competitions/", include("apps.competitions.urls")),
    path("goals/", include("apps.goals.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

apps/equipments/urls.py
from django.urls import path

from apps.equipments import views


urlpatterns = [
    path("", views.view_equipments, name="equipments"),

    path("add", views.view_equipment_create, name="add_equipment"),
    path("<id:sid>", views.view_equipment_info, name="equipment_info"),
    path("<id:sid>/edit", views.view_equipment_edit, name="equipment_edit"),
    #path("<int:sid>/edit", views.view_equipment_edit_redirect),
    path("<id:sid>/edit_activities", views.view_equipment_edit_activities, name="equipment_edit_activities"),
    path("<id:sid>/remove", views.view_equipment_remove, name="equipment_remove"),
    #path("<int:sid>/remove", views.view_equipment_remove_redirect),
    path("add_set", views.view_equipment_set_create, name="add_equipment_set"),
    path("set-<id:sid>/edit", views.view_equipment_set_edit, name="edit_equipment_set"),
    path("set-<id:sid>/remove", views.view_equipment_set_remove, name="remove_equipment_set"),
]

apps/equipments/models.py
import os

from django.db import models
from django.db.models import Sum
from django.utils.translation import gettext as _

from apps.base.globals import sports
from apps.equipments.globals import equipments
from apps.user.models import User

from Magni.storage import OverwriteStorage


def random_filename(instance, filename):
    ext = os.path.splitext(filename)[1].lower()
    if ext == ".jpeg":
        ext = ".jpg"
    filename = "equipment_%04d%s" % (instance.pk, ext)
    return filename


class Equipment(models.Model):
    type = models.CharField(_("equipment type"), max_length=16, choices=[(a, b["name"]) for a, b in equipments.items()], default="Other")
    brand = models.CharField(_("brand"), max_length=50)
    model = models.CharField(_("model"), blank=True, max_length=50)
    name = models.CharField(_("name"), blank=True, max_length=50)
    notes = models.TextField(_("notes"), blank=True, max_length=500)
    date = models.CharField(_("date"), max_length=10, blank=True)
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="equipments", on_delete=models.CASCADE)
    old = models.BooleanField(_("old equipment"), default=False)
    image = models.ImageField(verbose_name=_("Image"), storage=OverwriteStorage(), upload_to=random_filename, null=True, blank=True)
    # TODO: date end
    #cost ???

    def save(self, *args, **kwargs):
        if self.pk is None:
            saved_image = self.image
            self.image = None
            super(Equipment, self).save(*args, **kwargs)
            self.image = saved_image
            if "force_insert" in kwargs:
                kwargs.pop("force_insert")

        super(Equipment, self).save(*args, **kwargs)

    def __str__(self):
        name = str(self.name)
        if name:
            return "[%s] %s" % (equipments[str(self.type)]["name"], name)
        else:
            name = "[%s] %s" % (equipments[str(self.type)]["name"], str(self.brand))
            model = str(self.model)
            if model:
                name += " " + model
            if len(str(self.date)) >= 4:
                return "%s (%s)" % (name, self.date[0:4])
            else:
                return name

    def nname(self):
        name = str(self.name)
        if name:
            return name
        else:
            name = str(self.brand)
            model = str(self.model)
            if model:
                name += " " + model
            if len(str(self.date)) >= 4:
                return "%s (%s)" % (name, self.date[0:4])
            else:
                return name

    @property
    def distance(self):
        d = self.activities.aggregate(Sum("distance"))["distance__sum"]
        if d is None:
            return 0
        else:
            return d

    @property
    def duration(self):
        d = self.activities.aggregate(Sum("duration"))["duration__sum"]
        if d is None:
            return 0
        else:
            return d

    class Meta:
        verbose_name = _("Equipment")
        verbose_name_plural = _("Equipments")
        ordering = ["type", "-date"]


class EquipmentSet(models.Model):
    name = models.CharField(_("name"), max_length=50, blank=False, null=False)
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="equipmentsets", on_delete=models.CASCADE)
    equipments = models.ManyToManyField(Equipment, related_name="equipmentsets")
    type = models.CharField(_("activity type"), max_length=16, choices=[("All", _("All activities"))] + [(a, b["name"]) for a, b in sports.items()], default="All")

    class Meta:
        verbose_name = _("Equipment set")
        verbose_name_plural = _("Equipment sets")
        ordering = ["name"]

apps/equipments/forms.py
from django.forms import ModelForm
from django.forms import Textarea, TextInput, BooleanField, FileInput, HiddenInput, CharField
from django.utils.translation import gettext as _

from apps.equipments.models import Equipment, EquipmentSet


class EquipmentForm(ModelForm):
    #is_default = BooleanField(label=_("Default equipment"), required=False)  # TODO
    image_clear = CharField(widget=HiddenInput(), max_length=1, required=False, initial="0")

    def save(self, commit=True):
        image_clear_value = self.cleaned_data.get("image_clear")
        if image_clear_value == "1":
            self.instance.image = None

        return super(ModelForm, self).save(commit=commit)

    class Meta:
        model = Equipment
        fields = ["type", "brand", "model", "name", "date", "notes", "old", "image", "image_clear"]
        widgets = {
            "date": TextInput(attrs={"placeholder": "YYYY-MM-DD"}),
            "notes": Textarea(attrs={"rows": 4}),
            "image": FileInput(),
        }


class EquipmentSetForm(ModelForm):
    class Meta:
        model = EquipmentSet
        fields = ["name", "type", "equipments"]

apps/equipments/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from apps.equipments.forms import EquipmentForm, EquipmentSetForm
from apps.equipments.models import Equipment, EquipmentSet
from apps.equipments.globals import equipments
from apps.activities.models import Activity
from django.db.models import Sum, Count


@login_required
def view_equipments(request):
    equipments = Equipment.objects.filter(user=request.user)
    equipmentsets = EquipmentSet.objects.filter(user=request.user)
    return render(request, "equipments/equipments.html", {"equipments": equipments, "equipmentsets": equipmentsets})


@login_required
def view_equipment_info(request, sid):
    try:
        equipment = Equipment.objects.get(id=sid, user=request.user)
    except Equipment.DoesNotExist:
        return redirect("equipments")

    # Attention: order_by est indispensable car sinon Django ajoute la date dans la clause "GROUP BY" !
    stats = equipment.activities.values("type").annotate(total_distance=Sum("distance"), total_duration=Sum("duration"), total=Count("id")).order_by("type")

    return render(request, "equipments/equipment_info.html", {"equipment": equipment, "stats": stats})


@login_required
def view_equipment_create(request):
    if request.method == "POST":
        form = EquipmentForm(request.POST, request.FILES)
        if form.is_valid():
            equipment = form.save(commit=False)
            equipment.user = request.user
            equipment.save()

            """
            # TODO: user default equipments
            if form.cleaned_data["is_default"]:
                request.user.default_equipment = equipment
                request.user.save()
            """

            return redirect("equipment_info", equipment.id)
    else:
        form = EquipmentForm()

    return render(request, "equipments/equipment_create.html", {"form": form})


@login_required
def view_equipment_edit(request, sid):
    try:
        equipment = Equipment.objects.get(id=sid, user=request.user)
    except Equipment.DoesNotExist:
        return redirect("equipments")

    if request.method == "POST":
        form = EquipmentForm(request.POST, request.FILES, instance=equipment)
        if form.is_valid():
            form.save()

            # TODO: remove unused image

            """
            # TODO: user default equipments
            if form.cleaned_data["is_default"]:
                if request.user.default_equipment != equipment:
                    request.user.default_equipment = equipment
                    request.user.save()
            elif request.user.default_equipment == equipment:
                request.user.default_equipment = None
                request.user.save()
            """

            return redirect("equipment_info", equipment.id)
    else:
        #form = EquipmentForm(initial={"is_default": request.user.default_equipment == equipment}, instance=equipment)
        form = EquipmentForm(initial={"is_default": False}, instance=equipment)  # TODO: user default equipments

    return render(request, "equipments/equipment_edit.html", {"equipment": equipment, "form": form})


@login_required
def view_equipment_edit_activities(request, sid):
    try:
        equipment = Equipment.objects.get(id=sid, user=request.user)
    except Equipment.DoesNotExist:
        return redirect("equipments")

    activities_selected = equipment.activities.values_list("id", flat=True)

    # On sélectionne toutes les activités de l'utilisateur
    activities = Activity.objects.filter(user=request.user)

    # On ne garde que les activités effectuées après l'achat de l'équipement
    if equipment.date:
        activities = activities.filter(date__gte=equipment.date)

    # On filtre le type d'activité en fonction du type d'équipement
    if equipments[equipment.type]["sports"]:
        activities = activities.filter(type__in=equipments[equipment.type]["sports"])

    if request.method == "POST":
        new_selection = request.POST.getlist("activity")
        new_selection = [int(v) for v in new_selection]

        if new_selection != list(activities_selected):
            equipment.activities.clear()
            equipment.activities.add(*new_selection)

        return redirect("equipment_info", equipment.id)

    return render(request, "equipments/equipment_edit_activities.html", {
        "equipment": equipment,
        "activities": activities,
        "activities_selected": activities_selected,
    })


@login_required
def view_equipment_remove(request, sid):
    try:
        equipment = Equipment.objects.get(id=sid, user=request.user)
    except Equipment.DoesNotExist:
        return redirect("equipments")

    if request.method == "POST" and "delete" in request.POST:
        equipment.delete()
        return redirect("equipments")

    return render(request, "equipments/equipment_remove.html", {"equipment": equipment})


@login_required
def view_equipment_set_create(request):
    if request.method == "POST":
        form = EquipmentSetForm(request.POST)
        if form.is_valid():
            equipmentset = form.save(commit=False)
            equipmentset.user = request.user
            equipmentset.save()
            form.save_m2m()

            return redirect("equipments")
    else:
        form = EquipmentSetForm()

    return render(request, "equipments/equipment_set_create.html", {"form": form})


@login_required
def view_equipment_set_edit(request, sid):
    try:
        equipmentset = EquipmentSet.objects.get(id=sid, user=request.user)
    except EquipmentSet.DoesNotExist:
        return redirect("equipments")

    if request.method == "POST":
        form = EquipmentSetForm(request.POST, instance=equipmentset)
        if form.is_valid():
            form.save()
            return redirect("equipments")
    else:
        form = EquipmentSetForm(instance=equipmentset)

    return render(request, "equipments/equipment_set_edit.html", {"equipmentset": equipmentset, "form": form})


@login_required
def view_equipment_set_remove(request, sid):
    try:
        equipmentset = EquipmentSet.objects.get(id=sid, user=request.user)
    except EquipmentSet.DoesNotExist:
        return redirect("equipments")

    if request.method == "POST" and "delete" in request.POST:
        equipmentset.delete()
        return redirect("equipments")

    return render(request, "equipments/equipment_set_remove.html", {"equipmentset": equipmentset})

apps/equipments/templates/equipments/equipment_create.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load utils %}

{% block title %}{% translate 'Equipments' %} | {% endblock %}
{% block page_title %}{% translate 'New equipment' %}{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/fileinput.min.css' %}" media="all" />
{% endblock %}

{% block scripts %}
<script src="{% static 'js/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'js/fileinput/locales/fr.js' %}"></script>

<script>
$(function() {
    $('#id_image').fileinput({
        showPreview: true,
        previewFileType: 'image',
        allowedFileTypes: ['image'],
        showUpload: false,
        browseClass: 'btn btn-success',
        language: 'fr',
        maxFileCount: 1,
        autoReplace: true,
    });
});
</script>
{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="card-body">
      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
            <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Submit' %}" />
      <a href="{% url 'equipments' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

apps/equipments/templates/equipments/equipment_edit.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load utils %}

{% block title %}{% translate 'Equipments' %} | {% endblock %}
{% block page_title %}<a href="{% url 'equipments' %}">{% translate 'Equipments' %}</a> - <a href="{% url 'equipment_info' equipment.id %}">{{ equipment.nname }}</a>{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/fileinput.min.css' %}" media="all" />
{% endblock %}

{% block scripts %}
<script src="{% static 'js/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'js/fileinput/locales/fr.js' %}"></script>

<script>
$(function() {
    $('#id_image').fileinput({
        showPreview: true,
        previewFileType: 'image',
        allowedFileTypes: ['image'],
        showUpload: false,
        browseClass: 'btn btn-success',
        language: 'fr',
        maxFileCount: 1,
        autoReplace: true,
        {% if equipment.image %}
        initialPreview: [
            '{{ equipment.image.url }}',
        ],
        initialPreviewAsData: true,
        initialCaption: '',
        initialPreviewShowDelete: false,
        initialPreviewConfig: [
            {
                size: {{ equipment.image.size }},
                showDrag: false,
            },
        ],
        {% endif %}
    });
    {% if equipment.image %}
    $('#id_image').on('fileselect', function(event) {
        $('#id_image_clear').val('0');
    });
    $('#id_image').on('fileclear', function(event) {
        $('#id_image_clear').val('1');
    });
    {% endif %}
});
</script>
{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="card-body">
      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
            <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Submit' %}" />
      <a href="{% url 'equipments' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

apps/equipments/templates/equipments/equipment_edit_activities.html
{% extends 'base.html' %}

{% load i18n %}
{% load utils %}

{% block title %}{% translate 'Equipments' %} | {% endblock %}
{% block page_title %}<a href="{% url 'equipments' %}">{% translate 'Equipments' %}</a> - <a href="{% url 'equipment_info' equipment.id %}">{{ equipment.nname }}</a>{% endblock %}

{% block scripts %}
<script>
$(function() {

});
</script>
{% endblock %}

{% block content %}

<form action="{% url 'equipment_edit_activities' equipment.id %}" method="post">
{% csrf_token %}

<div class="card">
  <div class="card-header">
    {% translate 'Activities' %}
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped table-sm" id="activities">
      <thead>
        <tr>
          <th></th>
          <th>{% translate 'Name' %}</th>
          <th>{% translate 'Date' %}</th>
          <th>{% translate 'Type' %}</th>
          <th>{% translate 'Duration' %}</th>
          <th>{% translate 'Distance' %}</th>
        </tr>
      </thead>
      <tbody>
      {% for activity in activities.all %}
        <tr>
          <td><input type="checkbox" name="activity" value="{{ activity.id }}"{% if activity.id in activities_selected %} checked="checked"{% endif %} /></td>
          <td><a href="{% url 'activity' activity.id %}">{% if activity.name %}{{ activity.name }}{% else %}{{ activity.type|activity_name }}{% endif %}</a></td>
          <td><a href="{% url 'activity' activity.id %}">{{ activity.date_local|date_short }}</a>{% if activity.planned %} ({% translate 'planned' %}){% endif %}</td>
          <td><span class="badge" style="background-color: {{ activity.type|activity_bgcolor }}; color: {{ activity.type|activity_textcolor }};"><i class="fas fa-{{ activity.type|activity_icon }}"></i> {{ activity.type|activity_name }}</span></td>
          <td>{{ activity.duration|duration }}</td>
          <td>{{ activity.distance|distance }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="card-footer text-center">
    <input type="submit" class="btn btn-primary" value="{% translate 'Submit' %}" />
    <a href="{% url 'equipment_info' equipment.id %}" class="btn btn-default">{% translate 'Cancel' %}</a>
  </div>
</div>

</form>

{% endblock %}

apps/equipments/templates/equipments/equipment_remove.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate 'Equipments' %} | {% endblock %}
{% block page_title %}<a href="{% url 'equipments' %}">{% translate 'Equipments' %}</a> - <a href="{% url 'equipment_info' equipment.id %}">{{ equipment.nname }}</a>{% endblock %}

{% block content %}

<div class="card card-primary">
  <form action="" method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="delete" value="1" />

    <div class="card-body">
      <p>{% translate 'Equipment' %}{% translate ':' %} {{ equipment }}</p>

      <div class="alert alert-warning">
        <p>{% translate 'Are you sure you want to remove this equipment?' %}</p>
        <p><i class="icon fas fa-exclamation-triangle"></i>{% translate 'This action is irreversible.' %}</p>
      </div>
    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-danger" value="{% translate 'Remove' %}" />
      <a href="{% url 'equipments' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

apps/equipments/templates/equipments/equipment_set_create.html
{% extends 'base.html' %}

{% load i18n %}
{% load utils %}

{% block title %}{% translate 'Equipments' %} | {% endblock %}
{% block page_title %}{% translate 'New equipment set' %}{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post">
    {% csrf_token %}

    <div class="card-body">
      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
            <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Submit' %}" />
      <a href="{% url 'equipments' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

apps/equipments/templates/equipments/equipment_set_edit.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load utils %}

{% block title %}{% translate 'Equipments' %} | {% endblock %}
{% block page_title %}<a href="{% url 'equipments' %}">{% translate 'Equipments' %}</a> - {{ equipmentset.name }}{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post">
    {% csrf_token %}

    <div class="card-body">
      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
            <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Submit' %}" />
      <a href="{% url 'equipments' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}