Magni/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, register_converter

import apps.base.views


class IdUrlConverter:
    regex = "[0-9]{6}"

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return "%06d" % value


register_converter(IdUrlConverter, "id")


urlpatterns = [
    path("", apps.base.views.view_index, name="home"),
    path("privacy", apps.base.views.view_privacy, name="privacy"),

    path("activities/", include("apps.activities.urls")),
    path("user/", include("apps.user.urls")),
    path("equipments/", include("apps.equipments.urls")),
    path("weight/", include("apps.weight.urls")),
    path("competitions/", include("apps.competitions.urls")),
    path("goals/", include("apps.goals.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

apps/activities/urls.py
from django.urls import path

from apps.activities import views


urlpatterns = [
    path("", views.view_activities, name="activities"),
    path("create", views.view_activity_create, name="create_activity"),
    path("import", views.view_activity_import, name="import_activity"),
    path("files", views.view_files, name="files"),
    path("map", views.view_map, name="map"),
    path("records", views.view_records, name="records"),
    path("records/evolution", views.view_record_evolution, name="record_evolution"),
    path("threshold", views.view_threshold, name="threshold"),
    path("progression", views.view_progression, name="progression"),
    path("calendar", views.view_calendar, name="calendar"),

    # Notes
    path("add_note", views.view_note_create, name="add_note"),
    path("edit_note-<id:id>", views.view_note_edit, name="edit_note"),
    path("remove_note-<id:id>", views.view_note_remove, name="remove_note"),
    path("notes", views.view_notes, name="notes"),

    path("stats", views.view_stats, name="stats"),
    path("stats/json", views.view_api_stats, name="api_stats"),

    path("json", views.view_api_activities, name="api_activities"),

    # Activity views
    path("<id:aid>", views.view_activity, name="activity"),
    path("<int:aid>", views.view_activity_redirect),
    path("<id:aid>/edit", views.view_activity_edit, name="activity_edit"),
    path("<int:aid>/edit", views.view_activity_edit_redirect),
    path("<id:aid>/remove", views.view_activity_remove, name="activity_remove"),
    path("<int:aid>/remove", views.view_activity_remove_redirect),
    path("<id:aid>/export", views.view_activity_export, name="activity_export"),
    path("<int:aid>/export", views.view_activity_export_redirect),
    path("<id:aid>/add_file", views.view_activity_add_file, name="activity_add_file"),
    path("<int:aid>/add_file", views.view_activity_add_file_redirect),
    path("<id:aid>/track", views.view_activity_track, name="activity_track"),
    path("<int:aid>/track", views.view_activity_track_redirect),
    path("<id:aid>/edit_records", views.view_activity_edit_records, name="activity_edit_records"),
    path("<int:aid>/edit_records", views.view_activity_edit_records_redirect),

    # Files
    path("<id:aid>/file/<slug:hash>/download", views.view_activity_download_file, name="activity_download_file"),
    path("<id:aid>/file/<slug:hash>/remove", views.view_activity_remove_file, name="activity_remove_file"),
    path("<id:aid>/file/<slug:hash>/recalculate", views.view_activity_recalculate_file, name="activity_recalculate_file"),

    # Segments
    path("<id:aid>/add_segment", views.view_activity_add_segment, name="activity_add_segment"),
    path("<id:aid>/add_segments", views.view_activity_add_segments, name="activity_add_segments"),
    path("<id:aid>/edit_segment", views.view_activity_edit_segment, name="activity_edit_segment"),
    path("<id:aid>/remove_segment", views.view_activity_remove_segment, name="activity_remove_segment"),
]

apps/activities/models.py
import datetime
import json
import os

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.timezone import make_naive
from django.utils.translation import gettext as _

from Magni.settings import BASE_DIR
from apps.base.globals import sports
from apps.activities.trackfile import TrackFile
from apps.competitions.models import Competition
from apps.equipments.models import Equipment
from apps.user.models import User


class Activity(models.Model):
    date = models.DateTimeField(_("date"))
    name = models.CharField(_("name"), max_length=100, blank=True, null=True)
    time_shift = models.SmallIntegerField(_("time shift"), validators=[MinValueValidator(-12*60), MaxValueValidator(12*60)], default=0)
    type = models.CharField(_("activity type"), max_length=16, choices=[(a, b["name"]) for a, b in sports.items()], default="Other")
    planned = models.BooleanField(_("planned activity"), default=False)
    duration = models.PositiveIntegerField(_("duration"), blank=True, null=True)
    duration_total = models.PositiveIntegerField(_("total duration"), blank=True, null=True)
    distance = models.PositiveIntegerField(_("distance"), blank=True, null=True)
    notes = models.TextField(_("notes"), max_length=1000, blank=True)
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="activities", on_delete=models.CASCADE)
    device = models.CharField(_("device"), max_length=50, blank=True)
    heart_rate_avg = models.PositiveSmallIntegerField(_("average heart rate"), validators=[MaxValueValidator(220)], blank=True, null=True)
    heart_rate_max = models.PositiveSmallIntegerField(_("maximum heart rate"), validators=[MaxValueValidator(220)], blank=True, null=True)
    cadence_avg = models.PositiveSmallIntegerField(_("average cadence"), blank=True, null=True)
    cadence_max = models.PositiveSmallIntegerField(_("maximum cadence"), blank=True, null=True)
    power_avg = models.PositiveSmallIntegerField(_("average power"), blank=True, null=True)
    power_max = models.PositiveSmallIntegerField(_("maximum power"), blank=True, null=True)
    speed_avg = models.FloatField(_("average speed"), blank=True, null=True)
    speed_max = models.FloatField(_("maximum speed"), blank=True, null=True)
    calories = models.PositiveSmallIntegerField(_("calories"), blank=True, null=True)
    elevation_gain = models.PositiveIntegerField(_("elevation gain"), blank=True, null=True)
    elevation_loss = models.PositiveIntegerField(_("elevation loss"), blank=True, null=True)
    trimp = models.PositiveSmallIntegerField(_("TRIMP"), blank=True, null=True)
    level = models.PositiveSmallIntegerField(_("level"), blank=True, null=True)
    tss = models.PositiveSmallIntegerField(_("TSS"), blank=True, null=True)
    ngp = models.FloatField(_("NGP"), blank=True, null=True)
    feeling = models.PositiveSmallIntegerField(_("feeling"), default=0, validators=[MaxValueValidator(5)])
    exertion = models.PositiveSmallIntegerField(_("exertion"), default=0, validators=[MaxValueValidator(10)])
    equipments = models.ManyToManyField(Equipment, verbose_name=_("equipments"), related_name="activities", blank=True)
    competition = models.ForeignKey(Competition, verbose_name=_("competition"), related_name="activities", blank=True, null=True, on_delete=models.SET_NULL)
    data = models.TextField(_("data"), blank=True, null=True)  # format JSON

    # TODO: links

    def __init__(self, *args, **kwargs):
        self.trackfile = TrackFile()
        super(Activity, self).__init__(*args, **kwargs)

    def __str__(self):
        return "%s (%s) by %s" % (str(self.date), self.type, self.user)

    @property
    def date_local(self):
        return self.date.replace(tzinfo=None) + datetime.timedelta(seconds=self.time_shift * 60)

    @property
    def date_user(self):
        return make_naive(self.date)

    class Meta:
        verbose_name = _("Activity")
        verbose_name_plural = _("Activities")
        ordering = ["-date"]


def export_activity_json(activity):
    response = {
        "date": activity.date,
        "type": activity.type,
        "files": [],
    }

    if activity.duration is not None:
        response["duration"] = activity.duration
    if activity.duration_total is not None:
        response["duration_total"] = activity.duration_total
    if activity.distance is not None:
        response["distance"] = activity.distance
    if activity.notes:
        response["notes"] = activity.notes
    if activity.device is not None:
        response["device"] = activity.device
    if activity.trimp is not None:
        response["trimp"] = activity.trimp
    if activity.ngp is not None:
        response["ngp"] = activity.ngp
    if activity.speed_avg is not None:
        response["speed_avg"] = activity.speed_avg
    if activity.speed_max is not None:
        response["speed_max"] = activity.speed_max
    if activity.cadence_avg is not None:
        response["cadence_avg"] = activity.cadence_avg
    if activity.cadence_max is not None:
        response["cadence_max"] = activity.cadence_max
    if activity.power_avg is not None:
        response["power_avg"] = activity.power_avg
    if activity.power_max is not None:
        response["power_max"] = activity.power_max
    if activity.elevation_gain is not None:
        response["elevation_gain"] = activity.elevation_gain
    if activity.elevation_loss is not None:
        response["elevation_loss"] = activity.elevation_loss
    if activity.heart_rate_avg is not None:
        response["heart_rate_avg"] = activity.heart_rate_avg
    if activity.heart_rate_max is not None:
        response["heart_rate_max"] = activity.heart_rate_max
    if activity.calories is not None:
        response["calories"] = activity.calories
    if activity.feeling:
        response["feeling"] = activity.feeling
    if activity.exertion:
        response["exertion"] = activity.exertion

    if activity.data:
        try:
            data = json.loads(activity.data)
        except:
            data = {}

        if "records" in data and data["records"]:
            response["records"] = data["records"]
        if "pauses" in data and data["pauses"]:
            response["pauses"] = data["pauses"]
        if "heartrate_stats" in data and data["heartrate_stats"]:
            response["heartrate_stats"] = data["heartrate_stats"]
        if "power_stats" in data and data["power_stats"]:
            response["power_stats"] = data["power_stats"]
        if "segments" in data and data["segments"]:
            response["segments"] = data["segments"]

    response["equipments"] = []
    for equipment in activity.equipments.all():
        response["equipments"].append(str(equipment))

    if activity.competition:
        response["competition"] = activity.competition.name

    # Files
    for file in activity.files.all():
        response["files"].append({
            "name": file.filename,
            "sha1": file.filehash,
            "size": file.filesize,
            "compressed_size": file.compressed_size,
        })

    return response


class ActivityFile(models.Model):
    activity = models.ForeignKey(Activity, verbose_name=_("activity"), related_name="files", on_delete=models.CASCADE)
    filename = models.CharField(_("file name"), max_length=100)
    filehash = models.CharField(_("file hash"), max_length=40)
    filesize = models.PositiveIntegerField(_("file size"), default=0)
    compressed_size = models.PositiveIntegerField(_("compressed size"), default=0)
    # TODO: ajouter le format du fichier (TCX, FIT, etc.)
    # TODO: ajouter les types de données contenus dans le fichier (fréquence cardiaque, puissance, etc.)

    def __str__(self):
        return "%s \"%s\" (activity %s)" % (self.filehash, self.filename, self.activity)

    @property
    def downloadable(self):
        # Check if file is available in storage
        return os.path.isfile(self.get_path)

    @property
    def get_path(self):
        return os.path.join(BASE_DIR, "data", "files", str(self.filehash) + ".gz")

    class Meta:
        verbose_name = _("Activity file")
        verbose_name_plural = _("Activity files")
        unique_together = ("activity", "filehash")
        ordering = ["filename"]


class Note(models.Model):
    date_start = models.DateTimeField(_("start date"))
    date_end = models.DateTimeField(_("end date"), blank=True, null=True)
    title = models.CharField(_("title"), max_length=100)
    content = models.TextField(_("content"), max_length=1000, blank=True)
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="notes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Note")
        verbose_name_plural = _("Notes")
        ordering = ["date_start", "date_end"]

apps/activities/templates/activities/activities.html
{% extends 'base.html' %}
{% load i18n %}
{% load utils %}
{% load static %}
{% load tz %}

{% block title %}{% translate 'Activities' %} | {% endblock %}
{% block page_title %}{% translate 'Activities' %}{% endblock %}

{% block page_title_buttons %}
<div>
  <a href="{% url 'create_activity' %}" class="btn btn-primary btn-sm">{% translate 'Create activity' %}</a>
  <a href="{% url 'import_activity' %}" class="btn btn-primary btn-sm">{% translate 'Import activity' %}</a>
</div>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/datatables/datatables.css' %}" />
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-body">

    <div style="display: flex; flex-wrap: wrap; justify-content: flex-start; align-items: flex-start;">
      <div style="padding-right: 20px;">
        <label for="filter_sport">{% translate 'Activity type:' %}</label>
        <select id="filter_sport">
          <option value="" selected="selected">{% translate 'All' %}</option>
          {% for sport_code, sport in sports.items %}
            <option value="{{ sport_code }}">{{ sport.name }}</option>
          {% endfor %}
        </select>
      </div>
      <div style="padding-right: 20px;">
        <label for="filter_date-min">{% translate 'After:' %}</label>
        <input type="date" id="filter_date-min" />
      </div>
      <div style="padding-right: 20px;">
        <label for="filter_date-max">{% translate 'Before:' %}</label>
        <input type="date" id="filter_date-max" />
      </div>
    </div>

    <table class="table table-striped compact" id="activities" style="width:100%">
      <thead>
        <tr>
          <th>{% translate 'Name' %}</th>
          <th>{% translate 'Date' %}</th>
          <th>{% translate 'Type' %}</th>
          <th>{% translate 'Duration' %}</th>
          <th>{% translate 'Distance' %}</th>
          <th>{% translate 'Heart rate' %}</th>
          <th>{% translate 'Cadence' %}</th>
          <th>{% translate 'Power' %}</th>
          <th>{% translate 'TRIMP' %}</th>
          <th>{% translate 'TSS' %}</th>
          <th>{% translate 'Calories' %}</th>
          <th>{% translate 'Equipments' %}</th>
        </tr>
      </thead>
      <tbody>
      {% for activity in activities %}
        <tr>
          <td><a href="{% url 'activity' activity.id %}">{% if activity.name %}{{ activity.name }}{% else %}{{ activity.type|activity_name }}{% endif %}</a></td>
          <td><a href="{% url 'activity' activity.id %}">{{ activity.date_local|date_short }}</a>{% if activity.planned %} ({% translate 'planned' %}){% endif %}</td>
          <td><span class="badge" style="background-color: {{ activity.type|activity_bgcolor }}; color: {{ activity.type|activity_textcolor }};"><i class="fas fa-{{ activity.type|activity_icon }}"></i> {{ activity.type|activity_name }}</span></td>
          <td>{{ activity.duration|duration }}</td>
          <td>{{ activity.distance|distance }}</td>
          <td>{% if activity.heart_rate_avg %}{{ activity.heart_rate_avg }}{% endif %}</td>
          <td>{% if activity.cadence_avg %}{{ activity.cadence_avg }}{% endif %}</td>
          <td>{% if activity.power_avg %}{{ activity.power_avg }}{% endif %}</td>
          <td>{% if activity.trimp %}{{ activity.trimp }}{% endif %}</td>
          <td>{% if activity.tss %}{{ activity.tss }}{% endif %}</td>
          <td>{% if activity.calories %}{{ activity.calories }}{% endif %}</td>
          <td>{% if activity.equipments %}{{ activity.equipments }}{% endif %}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

  </div>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/datatables/datatables.js' %}"></script>

<script type="text/javascript">
$(function() {
  var type = 'All';
  var date_min = null;
  var date_max = null;

  var table = $('#activities').DataTable({
    language: {
      url: '{% static 'js/datatables/i18n/fr_FR.json' %}',
    },
    ajax: {
      url: '{% url 'api_activities' %}',
      data: function(d) {
        d.sport = type;
        if (date_min !== null)
          d.dateMin = date_min;
        if (date_max !== null)
          d.dateMax = date_max;
      },
    },
    serverSide: true,
    processing: true,
    stateSave: true,
    dom: 'Bfrtip',
    buttons: [
      'pageLength',
      {
        extend: 'colvis',
        columns: '2,3,4,5,6,7,8,9,10,11',
      },
    ],
    searching: false,
    responsive: true,
    ordering: true,
    order: [[ 1, 'desc' ]],
    paging: true,
    pageLength: 20,
    lengthMenu: [ [10, 20, 50, 100], [10, 20, 50, 100] ],
    columns: [
      {
        name: 'name',
        data: 'name',
        render: function(data, type, row) {
          if (type == 'sort') {
            return data;
          } else {
            return '<a href="' + row['url'] + '">' + data + '</a>';
          }
        },
      },
      {
        name: 'date',
        data: 'date_txt',
        render: function(data, type, row) {
          if (type == 'sort') {
            return row['date'];
          } else {
            return '<a href="' + row['url'] + '">' + data + '</a>';
          }
        },
      },
      {
        name: 'type',
        data: 'type_txt',
        render: function(data, type, row) {
          if (type == 'display') {
            return '<span class="badge" style="background-color: ' + row['bgcolor'] + '; color: ' + row['textcolor'] + ';"><i class="fas fa-' + row['icon'] + '"></i> ' + data + '</span>';
          } else {
            return data;
          }
        },
      },
      {
        name: 'duration',
        data: 'duration_txt',
      },
      {
        name: 'distance',
        data: 'distance_txt',
        render: function(data, type, row) {
          if (type == 'sort') {
            return row['distance'];
          } else {
            return data;
          }
        },
      },
      {
        name: 'heartrate',
        data: 'heartrate',
        visible: false,
      },
      {
        name: 'cadence',
        data: 'cadence',
        visible: false,
      },
      {
        name: 'power',
        data: 'power',
        visible: false,
      },
      {
        name: 'trimp',
        data: 'trimp',
      },
      {
        name: 'tss',
        data: 'tss',
      },
      {
        name: 'calories',
        data: 'calories',
        visible: false,
      },
      {
        name: 'equipments',
        data: 'equipments',
        visible: false,
        orderable: false,
      },
    ],
  });

  $('#filter_sport').val('');
  $('#filter_sport').change(function(e) {
    type = e.target.value;
    table.draw();
  });

  $('#filter_date-min').val('');
  $('#filter_date-min').change(function(e) {
    date_min = $(this).val();
    if (date_min === '') {
      date_min = null;
    }
    table.draw();
  });

  $('#filter_date-max').val('');
  $('#filter_date-max').change(function(e) {
    date_max = $(this).val();
    if (date_max === '') {
      date_max = null;
    }
    table.draw();
  });
});
</script>
{% endblock %}

apps/activities/templates/activities/activity_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load utils %}
{% load static %}

{% block page_title %}{% translate 'New activity' %}{% endblock %}

{% block page_title_buttons %}
<a href="{% url 'import_activity' %}" class="btn btn-primary btn-sm">{% translate 'Import activity' %}</a>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/jquery.timepicker/jquery.timepicker.css' %}" />
{% endblock %}

{% block content %}

<div class="card">
  <form action="" class="form-horizontal" method="post">
    {% csrf_token %}

    <div class="card-body">
      {% if form1.non_field_errors %}
        <div class="alert alert-warning">
          {{ form1.non_field_errors }}
        </div>
      {% endif %}

      {% if form1.subject.errors %}
        <ol>
          {% for error in form1.subject.errors %}
          <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form1.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form1.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

      <hr />

      {% if form2.non_field_errors %}
        <div class="alert alert-warning">
          {{ form2.non_field_errors }}
        </div>
      {% endif %}

      {% if form2.subject.errors %}
        <ol>
          {% for error in form2.subject.errors %}
          <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form2.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form2.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Submit' %}" />
      <a href="{% url 'activities' %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.timepicker/jquery.timepicker.js' %}"></script>
<script type="text/javascript">
$(function() {
  $('#id_planned').change(function(e) {
    if ($(this).is(':checked')) {
      $('#id_feeling').prop('disabled', true);
      $('#id_exertion').prop('disabled', true);
    } else {
      $('#id_feeling').prop('disabled', false);
      $('#id_exertion').prop('disabled', false);
    }
  });

  $('#id_type').change(function(e) {
    var type = $(this).val();
    // TODO: filter equipments
  });

  $('#id_date_time').timepicker({'timeFormat': 'H:i:s'});
});
</script>
{% endblock %}

apps/activities/templates/activities/activity_edit_segment.html
{% extends 'base.html' %}
{% load i18n %}
{% load tz %}
{% load utils %}

{% block title %}{% if activity.name %}{{ activity.name }}{% else %}{{ activity.type|activity_name }}{% endif %} - {{ activity.date_local|date_short }}{% if activity.planned %} ({% translate 'planned' %}){% endif %} | {% endblock %}
{% block page_title %}<i class="fas fa-{{ activity.type|activity_icon }}"></i> <a href="{% url 'activity' activity.id %}">{% if activity.name %}{{ activity.name }}{% else %}{{ activity.type|activity_name }}{% endif %} - {{ activity.date_local|date_long }}{% if activity.planned %} ({% translate 'planned' %}){% endif %}</a> - {% translate 'Edit segment' %}{% endblock %}

{% block content %}

<div class="card card-primary">
  <form action="" method="post" class="form">
    {% csrf_token %}

    <div class="card-body">
      {% if form.non_field_errors %}
        <div class="alert alert-warning">
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      {% if form.subject.errors %}
        <ol>
          {% for error in form.subject.errors %}
          <li><strong>{{ error }}</strong></li>
          {% endfor %}
        </ol>
      {% endif %}

      {% for field in form.hidden_fields %}
        {{ field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group{% if not field|is_checkbox %} row{% endif %}">
          {% if field|is_checkbox %}
            <div class="custom-control custom-switch">
              {% if field.errors %}
                {{ field|field_add_class_cb:'custom-control-input is-invalid' }}
              {% else %}
                {{ field|field_add_class_cb:'custom-control-input' }}
              {% endif %}
              <label for="{{ field.id_for_label }}" class="custom-control-label">{{ field.label }}</label>
            </div>
            {% if field.help_text %}
              <p class="form-text text-muted small">{{ field.help_text }}</p>
            {% endif %}
            {{ field.errors }}
          {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {% if field.errors %}
                {{ field|field_add_class:'form-control form-control-sm is-invalid' }}
              {% else %}
                {{ field|field_add_class:'form-control form-control-sm' }}
              {% endif %}
              {% if field.help_text %}
                <p class="form-text text-muted small">{{ field.help_text }}</p>
              {% endif %}
              {{ field.errors }}
            </div>
          {% endif %}
        </div>
      {% endfor %}
    </div>

    <div class="card-footer text-center">
      <input type="submit" class="btn btn-primary" value="{% translate 'Edit' %}" />
      <a href="{% url 'activity' activity.id %}" class="btn btn-default">{% translate 'Cancel' %}</a>
    </div>
  </form>
</div>

{% endblock %}